#!/bin/bash

cd
echo ""
echo "Сlick on allow to proceed"
termux-setup-storage & sleep 4 &>/dev/null

while true; do
    if [ -e storage ]; then
        rm -rf /sdcard/termux-box-native
        break
    else
        echo "If you denied permission, change it manually in termux app settings now"
    fi
    sleep 2
done

mkdir -p /sdcard/termux-box-native

echo ""
echo "Updating termux packages"
apt-get clean
apt-get update >/dev/null 2>&1
apt-get -y --with-new-pkgs -o Dpkg::Options::="--force-confdef" upgrade >/dev/null 2>&1

echo ""
echo "Installing necessary packages"
pkg install x11-repo -y &>/dev/null
pkg install pulseaudio -y &>/dev/null
pkg install xwayland -y &>/dev/null
pkg install proot -y &>/dev/null
pkg install wget -y &>/dev/null
pkg install tsu -y &>/dev/null
pkg install root-repo -y &>/dev/null

rm -rf $HOME/termux-box-native
mkdir -p $HOME/termux-box-native
cd $HOME/termux-box-native

if [ "$(ls $PREFIX | grep glibc)" == "glibc" ]
then
     echo -e "I have detected an already existing install. I will proceed to wipe it now".
     rm -rf /sdcard/glibc_prefix.tar.xz
     rm -rf /sdcard/wine-8.0-amd64.tar.xz
     rm -rf /sdcard/wine-8.14-amd64.tar.xz
     rm -rf $PREFIX/glibc
fi

#glibc_prefix install
[[ ! -f /sdcard/glibc_prefix.tar.xz ]] && wget https://github.com/Pipetto-crypto/androBox/releases/download/glibc_prefix/glibc_prefix.tar.xz -P /sdcard

if [ -f /sdcard/glibc_prefix.tar.xz ]
then
     tar -xf /sdcard/glibc_prefix.tar.xz -C $PREFIX
else
     echo -e "It seems that the glibc prefix didn't download properly, exiting now. Please make sure you have a good internet connection and retry"
     exit
fi

wget https://github.com/3x0d7s/termux-box-native/raw/main/components/termux-x11-1.02.07-0-all.deb &>/dev/null
dpkg -i termux-x11-1.02.07-0-all.deb &>/dev/null
rm -rf termux-x11-1.02.07-0-all.deb

echo "Downloading preconfigured Rootfs..."
cd $HOME/termux-box-native
wget -q --show-progress https://github.com/3x0d7s/termux-box-native/releases/download/0.0.1-alpha/rootfs.tar.xz

echo "Unzipping Rootfs..."
tar -xf rootfs.tar.xz
rm -rf rootfs.tar.xz

cd $HOME/termux-box-native/ubuntu-fs/opt
wget https://github.com/3x0d7s/termux-box-native/raw/main/scripts/scripts.tar.gz &>/dev/null
tar -xf scripts.tar.gz
rm -rf scripts.tar.gz

cd $HOME/termux-box-native/
wget -N https://github.com/3x0d7s/termux-box-native/raw/main/scripts/termux-box &>/dev/null
chmod +x termux-box-native
mv termux-box-native $PREFIX/bin/
wget -N https://github.com/3x0d7s/termux-box-native/raw/main/scripts/start-proot.sh &>/dev/null
wget -N https://github.com/3x0d7s/termux-box-native/raw/main/scripts/start-chroot.sh &>/dev/null
wget -N https://github.com/3x0d7s/termux-box-native/raw/main/scripts/start-native.sh &>/dev/null
chmod +x start-proot.sh
chmod +x start-chroot.sh
chmod +x start-native.sh

echo "Installing patch"

cd $HOME/termux-box-native/ubuntu-fs
wget -q --show-progress https://github.com/3x0d7s/termux-box-native/releases/download/0.0.1-alpha/patch.tar.xz
rm -rf opt/d3d
rm -rf opt/mesa
tar -xf patch.tar.xz
rm -rf patch.tar.xz
cd

echo "Starting termux-box-native now. Next time use \"termux-box-native\" command to run it."
sleep 2

rm -rf "$0"
exec $PREFIX/bin/termux-box-native
